name: github-action
env:
  apiKey: "17367bcc353b421e3b2a51d8"
  apiSecret: "f7f1e77340e84a3ed0b8c493fd228a1b75aa1b75d2a42f4855ad230918190a356cbb796b"
  #testID: "13797457"
  continuePipeline: "false"
  showTailLog: false
  uploadFileCheck: "true"
  inputStartFile: "taurus_1.yml"
  envVariable: '{"concurrency":"32","hold-for":"5m","ramp-up": "2m"}'
  #testRunByTestName: true
  #testName: "Untitled test January_05_1:45 PM"
  # testName: "Hello From Action"
  testID: "13744261"
  projectID: "1478138"
  
on: push
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: List Files
        run: ls $pwd
      - name: Set Environment Variable
        run: echo ${{github.workspace}}
      - name: HelloTestAction
        #uses: dnyanesh-nagre-perforce/blaze-action@v2.14
        uses: dnyanesh-nagre-perforce/blaze-action@v3.0.0
        id: run-test
        with:
          apiKey: ${{env.apiKey}}
          apiSecret: ${{env.apiSecret}}
          #testID: ${{env.testID}}
          # continuePipeline: ${{env.continuePipeline}}
          # showTailLog: ${{env.showTailLog}}
          # uploadFileCheck: ${{env.uploadFileCheck}}
          # inputstartfile: ${{env.inputStartFile}}
          envVariable: ${{env.envVariable}}
          # testRunByTestName: ${{env.testRunByTestName}}
          testID: ${{env.testID}}
          projectID: ${{env.projectID}}
          # createTest: ${{env.createTest}}
