name: github-action
env:
  apiKey: "17367bcc353b421e3b2a51d8"
  apiSecret: "f7f1e77340e84a3ed0b8c493fd228a1b75aa1b75d2a42f4855ad230918190a356cbb796b"
  testID: "13797457"
  continuePipeline: "false"
  showTailLog: "false"
  uploadFileCheck: "true"
  inputstartfile: "https://github.com/dnyanesh-nagre-perforce/blaze-action/blob/main/taurus_1.yml"
  
on: push
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: PerforceAction
        uses: dnyanesh-nagre-perforce/blaze-action@v2.3
        id: run-test
        with:
          apiKey: ${{env.apiKey}}
          apiSecret: ${{env.apiSecret}}
          testID: ${{env.testID}}
          continuePipeline: ${{env.continuePipeline}}
          showTailLog: ${{env.showTailLog}}
          uploadFileCheck: ${{env.uploadFileCheck}}
          inputstartfile: ${{env.inputstartfile}}
