name: github-action
env:
  apiKey: "3ee88ae5819c48e5e7555553"
  apiSecret: "b008253a717d32a3e69b4e6c5eaa46a4937c8b17ddfb30834b8c13e34b2b4e5a273c421c"
  #testID: "13797457"
  continuePipeline: "false"
  showTailLog: false
  uploadFileCheck: "true"
  inputStartFile: ".github/workflows/demo.jmx"
  # envVariable: '{"concurrency":"32","hold-for":"5m","ramp-up": "2m", "steps": "4"}'
  #testRunByTestName: true
  testName: "via GitHub Action-22"
  # testName: "Hello From Action"
  testID: "13744261"
  projectID: "1478138"
  createTest: "false"
  totalUsers: "39"
  duration: "4"
  rampUp: "2"
  steps: "0"
  throughput: "1"
  disableLoadConfig: "false"
  concurrencyControlEnabled: "true"
  iterationsEnabled: "true"
  iterations: "1"
  locations: "EU Central (Frankfurt)"
  
on: push
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: List Files
        run: ls $pwd
      - name: Set Environment Variable
        run: echo ${{env.steps}}
      - name: BlazeRunnerAction
        uses: Blazemeter/github-action@v8.6
      # - name: HelloTestAction
        #uses: dnyanesh-nagre-perforce/blaze-action@v2.14
        # uses: dnyanesh-nagre-perforce/blaze-action@v3.0.24
        id: run-test
        with:
          apiKey: ${{env.apiKey}}
          apiSecret: ${{env.apiSecret}}
          #testID: ${{env.testID}}
          # continuePipeline: ${{env.continuePipeline}}
          # showTailLog: ${{env.showTailLog}}
          uploadFileCheck: ${{env.uploadFileCheck}}
          inputstartfile: ${{env.inputStartFile}}
          # envVariable: ${{env.envVariable}}
          # testRunByTestName: ${{env.testRunByTestName}}
          testID: ${{env.testID}}
          # testName: ${{env.testName}}
          projectID: ${{env.projectID}}
          createTest: ${{env.createTest}}
          totalUsers: ${{env.totalUsers}}
          duration: ${{env.duration}}
          rampUp: ${{env.rampUp}}
          steps: ${{env.steps}}
          throughput: ${{env.throughput}}
          disableLoadConfig: ${{env.disableLoadConfig}}
          concurrencyControlEnabled: ${{env.concurrencyControlEnabled}}
          iterationsEnabled: ${{env.iterationsEnabled}}
          iterations: ${{env.iterations}}
          locations: ${{env.locations}}
